language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: udEpctP6KNSWoc78FzemMvmR2lG4vSHsynyKp07oDRT6VWIb/++OpYfSIm9whSGNDtN/vbevpi3Nt6AZOXokgvnSiXMuVVUvNzMFYKILSVTlwfXgNgwg5WcqlxZRemm2ivKY8w4wcbQAH59HzFvJ41dISBbcpKFmAYVyIzed0d/M2FQC8vMtFx68C7Q9Us4zRFCbmxRviVRLy4er0Oy+AvSqpXf1KeVUqQr+JgZqbvh+l9FgyTQKnMZ0XoyKyfzNfiTd50c+mefRumI0kwVDnI+kKvrINkikEM3GF6ARlnZL23TV1bBDyw+QjSd2xDHHZSDzyAZ7z+Oob/R5lZ4DEi6xw5OJNmyGT59CqEgcX7vD0Grqn438lLLkmRIFwqBzYC3i1NMfcyICZKajci9No8bdfk3Gf4B3XSy/DKo9kjKpB/6X5Rm3fkZp5Qd4NcYGD3k2Q9pi1EpX7BTt6BW38HHXMtGt17s9St1kZ2CbT9/vNifXT686zCkH/J6zLXV6xIOkEaefIAF9XgE/Vtumd3BJzLpsoJms2LSeDN/lbBbIn/ewEFnRqz2O02070EKXRThOQhL5Si1AcnNgOJzOP2Ajn1ZB86kY60Jssx4qLA9SvwFWyJq/TmdXQq/L6pprCzP+A9gOUkRGkj9MsBlv+mB75L2idSjzH9rFNyEF6BE=
  app: deal-hacker-api
  on:
    repo: RyanOkamuro/deal-hacker-api
